name: PR Checks

on: pull_request

jobs:
  Build:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Gradle build
        run: ./gradlew build -x test
      - name: Checkstyle linter
        run: ./gradlew checkstyleMain
      - name: Unit tests
        run: ./gradlew test
